version: "3.7"
services:
  # TODO: add kafka
  postgres:
    build:
      context: .
      dockerfile: pg_Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${RDS_USERNAME}
      - POSTGRES_PASSWORD=${RDS_PASSWORD}
      - POSTGRES_DB=${RDS_DB_NAME}
    restart: always
    volumes:
      - relational-db-data:/var/lib/postgresql/data/
volumes:
  relational-db-data:
