version: "3.7"
services:
  redis:
    container_name: "key-value-store"
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data'

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    build:
      context: .
      dockerfile: pg_Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${RDS_USERNAME}
      - POSTGRES_PASSWORD=${RDS_PASSWORD}
      - POSTGRES_DB=${RDS_DB_NAME}
    restart: always
    volumes:
      - relational-db-data:/var/lib/postgresql/data/
volumes:
  relational-db-data:
  redis:
